In [1]:
import pandas as pd

rfm_scaled = pd.read_csv("../outputs/rfm_scaled.csv")
nlp_features = pd.read_csv("../outputs/nlp_features.csv")

print("RFM shape:", rfm_scaled.shape)
print("NLP shape:", nlp_features.shape)

rfm_scaled.head()

RFM shape: (95420, 4)
NLP shape: (39322, 3)

                 customer_unique_id   recency  frequency  monetary
0  0000366f3b9a7992bf8c76cfdf3221e2  0.157967        0.0  0.009603
1  0000b849f77a49e4a4ce2b2a4ca5be3f  0.162088        0.0  0.001343
2  0000f46a3911fa3c0805444483337064  0.743132        0.0  0.005071
3  0000f6ccb0745a6a4b88665a16c9f078  0.446429        0.0  0.001871
4  0004aac84e0df4da2b147fca70cf8255  0.401099        0.0  0.013330

In [2]:
# Merge on customer_unique_id
X_full = rfm_scaled.merge(
    nlp_features,
    on="customer_unique_id",
    how="inner"
)

print("Fused feature shape:", X_full.shape)
X_full.head()

Fused feature shape: (39322, 6)

,customer_unique_id,recency,frequency,monetary,nlp_1,nlp_2
0,0000366f3b9a7992bf8c76cfdf3221e2,0.157967,0.0,0.009603,7.955969,0.534592
1,0000f6ccb0745a6a4b88665a16c9f078,0.446429,0.0,0.001871,13.129206,11.164166
2,00053a61a98854899e70ed204dd4bafe,0.255495,0.0,0.028361,4.529376,4.633020
3,0005ef4cd20d2893f0d9fbd94d3c0d97,0.239011,0.0,0.007742,5.494314,1.528532
4,0006fdc98a402fceb4eb0ee528f6a8d4,0.564560,0.0,0.000971,5.508366,-0.480954

In [3]:
X_full.to_csv(
    "../outputs/fused_features.csv",
    index=False
)

print("Feature fusion completed.")

Feature fusion completed.